name: CI + CD

on:
  workflow_dispatch:   

jobs:
  ssh:
    name: Automatism
    uses: ./.github/workflows/ssh.yml
    secrets:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}